name: Models Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-model-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Run Model data extractor script
        run: python scrapers/scrape_models.py

      - name: Commit model files
        run: |
          git add .
          git commit -m "Update car and bike model data"
          git push
